
-- member 테이블 생성
drop table if exists member CASCADE;
create table member
( id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

-- 초기 데이터 추가
insert into member(name) values('장도훈');

-- Test를 위한 명령어 
delete from MEMBER where NAME = 'spring'